[project]
name = "fastopenapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi-xml>=1.1.1",
    "fastapi>=0.115.2",
    "schemathesis>=3.37.0",
    "uvicorn>=0.32.0",
    "xmltodict>=0.14.2",
]
